---
- name: webserver setup
  hosts: web01
  become: yes
  tasks:
    - name: Install https
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: Start service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: Remove all files in /var/log/html
      ansible.builtin.shell: |
        cd /var/log/html; rm -rf *; ls /var/log/html
      args:
        chdir: somedir/
    - name: Copy artifact
      ansible.builtin.copy:
        src: ~/src/
        dest: /var/www/html/
