name: Set Sample WebApp
on: workflow_dispatch
env:
    PEM_FILE: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
    AppDeploy:
        runs-on: ubuntu-latest
        defaults: 
            run:
              shell: bash
              working-directory: ./ansible

        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: check path
              run: pwd
            - name: check files
              run: ls -al
            - name: Set up SSH key
              run: |
                echo "$PEM_FILE" > key.pem
                chmod 600 key.pem
            # - name: display key
            #   run: cat client.pem
            - name: check files
              run: ls -al
            - name: run ping playbook
              id: ping
              run: ansible-playbook ping_test.yaml 

              