name: Set Sample WebApp
on: 
    push: 
      branches: 
        - main
      paths: 
        - ansible/**
        - src/**

env:
    PEM_FILE: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
    AppDeploy:
        runs-on: ubuntu-latest
        defaults: 
            run:
              shell: bash
            
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: check path
              run: pwd
            - name: check files
              run: ls -al
            - name: Set up SSH key
              run: echo "$PEM_FILE" > ~/key.pem   
            - name: Chnage permission for key file
              run: chmod 600 ~/key.pem
            - name: copy config and inventory files
              run: cp ./ansible/ansible.cfg ./ansible/inventory.yaml  ~/
            - name: verify ansible config file
              run: cat ~/.ansible.cfg
            - name: run ping playbook
              id: ping
              run: ansible-playbook ./ansible/ping_test.yaml  
            - name: run setup playbook
              id: setup
              if: steps.ping.outcome == 'success'
              run: ansible-playbook ./ansible/setup.yaml 
              