name: Set Sample WebApp
on: workflow_dispatch
jobs:
    AppDeploy:
        runs-on: ubuntu-latest
        defaults: 
            run:
              shell: bash
              working-directory: ./ansible
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: check path
              run: pwd
            - name: check files
              run: ls -al
            - name: copy ppk
              run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./client.pem
            - name: display key
              run: cat client.pem
            - name: check files
              run: ls -al
            - name: run ping playbook
              uses: saubermacherag/ansible-playbook-docker-action@v1.4
              with:
                playbookName: 'ping.yaml'
                inventoryFile: 'inventory.yaml'
                keyFile: "client.pem"
                verbosity: "vv"
              